
'use server';
/**
 * @fileOverview A flow for emailing the End of Day (EOD) report.
 * - emailEodReport - A function that handles generating and emailing the EOD report.
 */
import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { generateEodReportFile, getEodReport } from '@/services/eod-service';
import { format, parse } from 'date-fns';
import { getStore } from '@/services/store-service';
import { getStoreInventory } from '@/services/inventory-service';
import { getSystemSettings } from '@/services/settings-service';
import { sendEmail } from '@/services/email-service';
import { isEmailOutboundEnabled } from '@/lib/email-feature';

const EmailEodReportInputSchema = z.object({
  storeId: z.string(),
  reportDate: z.string().describe("The date of the report in 'yyyy-MM-dd' format."),
});

export async function emailEodReport(storeId: string, reportDate: string): Promise<void> {
  // The date is now passed as a 'yyyy-MM-dd' string.
  return emailEodReportFlow({ storeId, reportDate });
}

const emailEodReportFlow = ai.defineFlow(
  {
    name: 'emailEodReportFlow',
    inputSchema: EmailEodReportInputSchema,
    outputSchema: z.void(),
  },
  async ({ storeId, reportDate }) => {
    if (!isEmailOutboundEnabled()) {
      throw new Error(
        'Outbound email is disabled. Set NEXT_PUBLIC_EMAIL_OUTBOUND_ENABLED=true after you configure email delivery.'
      );
    }

    // Parse the date string into a Date object, treating it as local time.
    const date = parse(reportDate, 'yyyy-MM-dd', new Date());
    
    const report = await getEodReport(storeId, date);
    if (!report) {
      throw new Error(`Could not find an EOD report for ${storeId} on ${format(date, 'PPP')}.`);
    }

    const [store, inventory, settings] = await Promise.all([
        getStore(report.storeId),
        getStoreInventory(report.storeId),
        getSystemSettings()
    ]);

    if (!store) {
      throw new Error("Store not found for the report.");
    }
    
    const recipient = settings?.eodReportRecipient;
    if (!recipient) {
      throw new Error("No EOD report recipient email is configured. Please set it in System Settings.");
    }

    const { fileData, fileName } = await generateEodReportFile({
      report,
      inventory,
      storeName: store.name,
    });

    const subject = `EOD Report for ${store.name} - ${format(report.date, 'PPP')}`;
    const htmlBody = `
      <h1>End of Day Report</h1>
      <p>Please find the EOD report for <strong>${store.name}</strong> on <strong>${format(report.date, 'PPP')}</strong> attached.</p>
      <p>Report generated by: ${report.generatedByName}</p>
    `;

    await sendEmail({
      to: recipient,
      subject,
      html: htmlBody,
      attachments: [
        {
          filename: fileName,
          content: fileData.toString('base64'),
          contentType: 'application/vnd.oasis.opendocument.spreadsheet',
        },
      ],
    });
  }
);
